# Generated by Django 4.1 on 2023-04-21 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="movies",
            fields=[
                ("movies", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("image", models.ImageField(default="default.png", upload_to="pics")),
                ("date", models.DateField()),
                ("duration", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=50)),
                ("rating", models.CharField(max_length=50)),
                ("cast", models.TextField(max_length=100)),
                ("trailer", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="screen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen", models.IntegerField()),
                ("type", models.CharField(max_length=50)),
                ("no_of_total_seats", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="shows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_time", models.TimeField()),
                ("show_date", models.DateField()),
                ("no_of_free_seats", models.IntegerField()),
                (
                    "movies",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tickets.movies"
                    ),
                ),
                (
                    "screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tickets.screen"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="theatre",
            fields=[
                ("theatre", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=50)),
                ("number_of_screens", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_customer", models.CharField(max_length=30)),
                ("age", models.SmallIntegerField()),
                ("no_of_seats", models.IntegerField()),
                (
                    "shows",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tickets.shows"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shows",
            name="theatre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tickets.theatre"
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="theatre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tickets.theatre"
            ),
        ),
    ]
