# Generated by Django 4.1 on 2023-04-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_screen_name_shows_price"),
    ]

    operations = [
        migrations.RemoveField(model_name="screen", name="screen",),
    ]
