# Generated by Django 4.1 on 2023-04-26 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tickets", "0005_remove_screen_screen"),
    ]

    operations = [
        migrations.CreateModel(
            name="ticket1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_customer", models.CharField(max_length=30)),
                ("age", models.SmallIntegerField()),
                ("no_of_seats", models.IntegerField()),
                (
                    "shows",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tickets.shows"
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="ticket",),
    ]
