# Generated by Django 4.1 on 2023-04-28 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_ticket1_delete_ticket"),
    ]

    operations = [
        migrations.RemoveField(model_name="theatre", name="number_of_screens",),
    ]
