# Generated by Django 4.1 on 2023-04-28 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_remove_theatre_number_of_screens"),
    ]

    operations = [
        migrations.RemoveField(model_name="shows", name="theatre",),
    ]
