# Generated by Django 4.1 on 2023-04-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0009_alter_screen_no_of_total_seats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="no_of_total_seats",
            field=models.IntegerField(null=True),
        ),
    ]
