# Generated by Django 4.1 on 2023-04-28 15:12

from django.db import migrations, models
from django.db.migrations.operations import RunSQL

class Migration(migrations.Migration):
    trigger_sql = """
        CREATE TRIGGER added
        AFTER INSERT ON tickets_theatre
        BEGIN
            INSERT INTO tickets_theatre1 (name) VALUES (new.name );
        END;
        """

    dependencies = [
        ("tickets", "0010_alter_screen_no_of_total_seats"),
    ]

    operations = [
        migrations.CreateModel(
            name="theatre1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="screen", name="no_of_total_seats", field=models.IntegerField(),
        ),RunSQL(trigger_sql),
    ]
